#!/bin/bash

if [ "$2" ]; then
  GITUSER="$2"
fi
if [ ! "$1" ] || [ ! "$GITUSER" ]; then
  echo "Usage: clone <directory> [git user]" > /dev/stderr
  exit 1
fi
echo "Cloning $1 from github.com"
git clone "https://github.com/$GITUSER/$1.git"