#!/bin/bash

if [ "$2" ]; then
  GITUSER="$2"
fi
if [ ! "$1" ] || [ ! "$GITUSER" ]; then
  echo "Usage: clone <directory> [user] [https]" > /dev/stderr
  exit 1
fi

if [ "$3" ]; then
  echo "Cloning $1 from github.com using HTTPS"
  git clone "https://github.com/$GITUSER/$1.git"
else
  echo "Cloning $1 from github.com using SSH"
  git clone "git@github.com:$GITUSER/$1.git"
fi
