#!/bin/bash

if [ "$2" ]; then
  GIT_USER="$2"
fi
if [ ! "$1" ] || [ ! "$GIT_USER" ]; then
  echo "Usage: $0 <directory> [user] [https]" > /dev/stderr
  exit 1
fi

if [ "$3" ]; then
  echo "Cloning $1 from github.com using HTTPS"
  git clone "https://github.com/$GIT_USER/$1.git"
else
  echo "Cloning $1 from github.com using SSH"
  git clone "git@github.com:$GIT_USER/$1.git"
fi
