#!/bin/bash

declare -A DYNDNS2=(
  ['badauth']='User or password incorrect'
  ['!donator']='No enough privileges'
  ['good']='Update successful'
  ['nochg']='Update successful. No changes'
  ['notfqdn']='Hostname is erroneous'
  ['nohost']='Hostname not found'
  ['numhost']='Too many hosts specified'
  ['abuse']='Hostname is blocked'
  ['badagent']='Agent-related error'
  ['dnserr']='DNS Error'
  ['911']='Under maintenance'
)
SUCCESS=('good' 'nochg')

dns_status()
{
  if [[ "${SUCCESS[@]}" =~ "$1" ]]; then
    echo "0"
  else
    echo "1"
  fi
}

if [ "$#" -lt 3 ]; then
  echo "Usage: $0 <username> <password> <hostname>" 1> /dev/stderr
  exit 1
fi
VAL=$(curl -s --user "$1:$2" "https://www.dnsdynamic.org/api/?hostname=$3&myip=$(myip)")
echo "$VAL: ${DYNDNS2[$VAL]}"
exit $(dns_status $VAL)
