#!/bin/bash

declare -A DYNDNS2=(
  ['badauth']='User or password incorrect'
  ['!donator']='No enough privileges'
  ['good']='Update successful'
  ['nochg']='Update successful. No changes'
  ['notfqdn']='Hostname is erroneous'
  ['nohost']='Hostname not found'
  ['numhost']='Too many hosts specified'
  ['abuse']='Hostname is blocked'
  ['badagent']='Agent-related error'
  ['dnserr']='DNS Error'
  ['911']='Under maintenance'
)
SUCCESS=('good' 'nochg')

dns_exit_status()
{
  if [[ "${SUCCESS[@]}" =~ "$1" ]]; then
    echo "0"
  else
    echo "1"
  fi
}

if [ ! "$2" ]; then
  echo "Usage: $0 <username> <hostname>" > /dev/stderr
  exit 1
fi

USER="$1"
HOST="$2"
read -s PASS

if [ ! "$PASS" ]; then
  echo "Missing password, abort." > /dev/stderr
  exit 1
fi

VAL=$(curl -s --user "$USER:$PASS" "https://www.dnsdynamic.org/api/?hostname=$HOST&myip=$(myip)")
STR="${DYNDNS2[$VAL]}"
if [ "$STR" ]; then
  echo "$STR"
else
  echo "$VAL"
fi
exit $(dns_exit_status "$VAL")
