#!/bin/bash

dns_status()
{
  if [ "$1" = "OK" ]; then
    echo "0"
  else
    echo "1"
  fi
}

if [ ! "$2" ]; then
  echo "Usage: $0 <token> <hostname>" > /dev/stderr
  exit 1
fi
VAL=$(curl -s "https://www.duckdns.org/update?token=$1&domains=$2")
exit $(dns_status $VAL)
