#!/bin/bash

DIR=$(arg_if_null "$1" ".")
COUNT=$(arg_if_null "$2" 1)
PLAYLIST=playlist.dat

(find "$DIR" -type f ! -name '*.srt' 2> /dev/null | shuf -n $COUNT) > $PLAYLIST

while read -r FILE; do
  ./vlc_enqueue "$FILE" 2> /dev/null &
done < $PLAYLIST
rm -f $PLAYLIST
