#!/bin/bash

FILE=$(arg_if_null "$1" ".vlc.$$.m3u")

cleanup()
{
  rm -f "$FILE"
}

trap cleanup SIGINT

touch "$FILE"
while read LINE; do
  echo "$LINE" >> "$FILE"
done
vlc_enqueue "$FILE" 2> /dev/null
cleanup
