#!/usr/bin/env python

import sys
import requests
from bs4 import BeautifulSoup

HOST = "https://zooqle.com"

def name(html):
  return html.find("a", class_="small").string

def seeders(html):
  return html.find("div", class_="progress-bar smaller prog-green prog-l").string

def leechers(html):
  return html.find("div", class_="progress-bar smaller prog-yellow prog-r").string

def size(html):
  return html.find("div", class_="progress-bar prog-blue prog-l").string

def torrent(html):
  return HOST + html.find(href=(lambda x: x and x.endswith(".torrent")))["href"]

def link(html):
  return HOST + html.find("a", class_="small")["href"]

try:
  show_id = sys.argv[1]
  season = sys.argv[2]
  episode = sys.argv[3]
except:
  print(sys.argv[0], "<show_id> <season> <episode>")
  sys.exit(1)

response = requests.get(HOST + "/misc/tveps.php?show=" + str(show_id) + "&se=" + str(season) + "&ep=" + str(episode))

if response.status_code != 200:
  sys.exit(1)

soup = BeautifulSoup(response.content, 'html.parser')
for tr in soup.find_all("tr"):
  try:
    if not tr.has_attr("style"):
      print("{}\t{}\t{}:{}\t{}\t{}".format(name(tr), size(tr), seeders(tr), leechers(tr), torrent(tr), link(tr)), flush=True)
  except:
    pass
